### ISSUE TITLE
GPU memory doesn't enough for the second launch  

### ISSUE THREAD

**Issue by ValeriiBaidin** [ericproffitt/TopicModelsVB.jl#34]
Hi.  

1. I have gpuLDA model
2. train1(...)
3....
4. I want to run train1(..) the second time, but "Julia has exited" or Error with gpu memory. 

I tried it several times. 
How to empty GPU memory before train!(...) or why the model is loading to memory second times?

Thank you in advance.

P.S. I have 4gb GPU, after 1st usgin train 3.2 GPU is been using.

**Comment by ericproffitt** [comment]
Hi Valerii,

Could you post the code you're running?

Unless more than once GPU model is being instantiated, there shouldn't be any double loading of GPU memory.

**Comment by ValeriiBaidin** [comment]
> Hi Valerii,
> 
> Could you post the code you're running?
> 
> Unless more than one GPU model is being instantiated, there shouldn't be any double loading of GPU memory.

```
model = gpuLDA(mc, 10)
train!(model,iter=150,  tol=0) #here 3.2gb gpu is used
showtopics(model, cols=10, 10)
train!(model,iter=1,  tol=0) #here is problem.

```

**Comment by ericproffitt** [comment]
I'm able to repeatedly train the full NSF corpus without ever hitting a GPU memory error on my machine. This may be a machine/GPU specific problem, it's difficult to tell.

If you want to try to debug this yourself, the problem is likely occuring in the `update_buffer!` function starting on line 373 of _modelutils.jl_.

If you're sure that this is the problem, then is there a way for you to manually clear your GPU memory between runs? This will not affect the model, as everytime `train!` finishes the data is read back into your CPU RAM, and then when you run `train!` again, the GPU buffers are reloaded from CPU memory.
